name: Build Tone RPMs

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-tone-rpms.yml
      - audiobookshelf-rpm.key
      - tone.spec

concurrency:
  group: audiobookshelf-rpmbuild
  cancel-in-progress: false

jobs:
  build:
    strategy:
      matrix:
        osversion:
          - '8'
          - '9'
    name: build (el${{ matrix.osversion }})
    runs-on: ubuntu-latest
    container:
      image: quay.io/centos/centos:stream${{ matrix.osversion }}
    steps:
      - name: install tools
        run: >
          dnf install -y
          createrepo
          git
          gnupg
          rpmdevtools
          rpm-sign

      - name: clone repository
        uses: actions/checkout@v4

      - name: prepare git
        run: |
          git config --global user.name "Deployment Bot"
          git config --global user.email "bot@lkiesow.dev"

      - name: prepare gpg
        env:
          GPG_KEY: ${{ secrets.GPG_KEY }}
        run: |
          echo "${GPG_KEY}" | gpg --import
          echo '%_gpg_name 1E8091C566FF00D9356DAE35D340FB28EF9633AE' > ~/.rpmmacros

      - name: prepare build tree
        run: |
          rpmdev-setuptree

      - name: download sources
        run: |
          spectool -g -R tone.spec

      - name: build rpm
        run: |
          rpmbuild -ba tone.spec

      - name: switch to repository branch
        run: |
          chown root:root .
          git fetch
          git checkout el${{ matrix.osversion }}

      - name: sign rpms
        run: |
          rpmsign --addsign ~/rpmbuild/RPMS/x86_64/*.rpm

      - name: copy rpms to repository
        run: |
          cp -v ~/rpmbuild/RPMS/x86_64/*.rpm .

      - name: add new rpms
        run: |
          git add ./*.rpm

      - name: update repository metadata
        run: |
          createrepo --update .
          git add ./repodata/

      - name: commit changes
        run: |
          git status
          RPM="$(ls -1 ~/rpmbuild/RPMS/x86_64/ | tail -n1)"
          git diff --staged --quiet || git commit -m "Build ${RPM} $(date)"

      - name: push updates
        run: |
          git remote -v
          git push

      - name: Setup Matrix
        uses: lkiesow/matrix-notification@v1
        with:
          room: '!gwaqKjZRpCQkpkTVwh:matrix.org'
          token: ${{ secrets.MATRIX_TOKEN }}
          tool: true

      - name: send notification
        run: |
          RPM="$(ls -1 ~/rpmbuild/RPMS/x86_64/ | tail -n1)"
          matrix-msg "Finished building ${RPM} for Audiobookshelf"
