name: Auto Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: prepare git
      run: |
        git config --global user.name "Lars' RPM Bot"
        git config --global user.email "bot@lkiesow.de"

    - name: prepare github ssh key
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      run: |
        install -dm 700 ~/.ssh/
        echo "${DEPLOY_KEY}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: clone repository
      run: |
        git clone -b main --single-branch "git@github.com:lkiesow/audiobookshelf-rpm.git" audiobookshelf-rpm-clone

    - name: update specs
      working-directory: audiobookshelf-rpm-clone
      run: |
        .github/update-audiobookshelf

    - name: push updates
      working-directory: audiobookshelf-rpm-clone
      run: |
        git push origin main
